theme = "mainroad"
defaultContentLanguage = "ja"
baseurl = "https://www.soudegesu.com"
#defaultContentLanguageInSubdirto = true

enableEmoji = true
paginate = "10"
publishDir = "docs"
enableRobotsTXT = true
disqusShortname = "soudegesu"
googleAnalytics = "G-S6WHJPSK6V"
hasCJKLanguage = true

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[Author]
    name = "soudegesu"
    bio = "Software Engineer"
    avatar = "/images/soudegesu.jpg"
    twitter = "alten_manten"

[Params]
    opengraph = true
    schema = true
    twitter_cards = true
    readmore = true
    homeLayout = "content + sidebar" # Configure home page layout
    listLayout = "content + sidebar" # Configure layout for list pages
    singleLayout = "content + sidebar" # Configure layout for single pages
    authorbox = true
    toc = true
    pager = true
    post_navigation = true
    post_meta = ["author", "date", "categories", "translations"]
    postSections = ["post", "past"]
    mainSections = ["post", "past"]
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages
    #dateformat = "2006-01-02" # change the format of dates
    #mathjax = true # Enable MathJax
    #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path
    #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
    googleSiteVerification = "cTEFKilSiC4rSg768JEVSgidHaZ0Kq9fbgnqqOYW9Uw"
    bingSiteVerification = "C58B4D4C2D3C5B99C7CF26F79733F9EB"
    yandexSiteVerification = "2f79a5310dc24118"
    googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700"

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  # facebook = "username"
  twitter = "alten_manten"
  # instagram = "username"
  # linkedin = "username"
  # telegram = "username"
  github = "soudegesu"
  # gitlab = "username"
  # bitbucket = "username"
  # email = "example@example.com"

[Languages]
[Languages.ja]
    languageName = "日本語"
    languageCode = "ja-JP"
    title = "そうなんでげす"
[Languages.ja.params]
    description = "soudegesuのtechブログ。普段仕事では使わない技術を中心に書いていくので入門系記事が多くなると思っていたけど、書き始めたらいい感じにいろいろまぜこぜになってきました。とりあえず、書きたくなったらいろいろ書きます。"
    subtitle = "またつまらぬモノを斬ってしまった"
[Languages.en]
    languageName = "English"
    languageCode = "en-US"
    title = "Sou-Nan-De-Gesu"
[Languages.en.params]
    description = "soudegesu tech blog. As I usually write about technologies that I do not use at work, I thought that there will be more introductory articles, but as I started writing, various things have become miscellaneous. Anyway, I write various things when I want to write."
    subtitle = "Once again, I cut a worthless object"

[markup.goldmark.renderer]
    unsafe = true
