# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: そうなんでげす
locale: "ja-JP"
name: "soudegesu"
email: your-email@domain.com
description: "記憶力足りないので、書いておくメモ"
url: "https://soudegesu.github.io"
baseurl: "/blog"
twitter_username: alten_manten
github_username: soudegesu
repository: "soudegesu/blog"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
gems:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

defaults:
  - scope:
    path: ""
    type: posts
  values:
    author_profile: true
    layout: single
    read_time: true
    comments: true
    share: true
    related: true

# Site Author
# see _data/authors.yml
author: soudegesu

# Social Link
social:
  type: "Person"
  links:
    - "https://twitter.com/alten_manten"
#    - "https://facebook.com/yourFacebook"
#    - "https://www.linkedin.com/in/yourprofile"
#    - "https://plus.google.com/your_profile"

# Analytics Tag
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-1234567-8"

# Timezone
timezone: Asia/Tokyo

# Archives
category_archive:
  type: jekyll-archives  # liquid から jekyll-archives に変更する
  path: /categories/
tag_archive:
  type: jekyll-archives  # liquid から jekyll-archives に変更する
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Pagenation
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num

# Compression
compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment
